name: Build

on: push

jobs:
  build:
    name: Build
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@nix_version_opt
    secrets:
      nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}
    with:
      filter_builds: '.system == "x86_64-linux"'
      label_builds: '"\(.attr)"'
